import type { ERSchema, ERColumn } from '@/lib/types';
import { generateSQL } from './exportSql';

type DummyData = Record<string, Record<string, any>[]>;

/**
 * Exports SQL CREATE TABLE + INSERT INTO statements with dummy data.
 * Uses the same fully-MySQL-compatible CREATE TABLE generation as exportSql.ts
 */
export function exportToSQLWithData(
    schema: ERSchema,
    dummyData: DummyData,
    projectName: string = 'database'
): void {
    const sql = generateSQLWithData(schema, dummyData);
    downloadSQL(sql, projectName);
}

function generateSQLWithData(schema: ERSchema, dummyData: DummyData): string {
    const lines: string[] = [];

    // Re-use the fully-correct CREATE TABLE generation (InnoDB, FK indexes, topo sort etc.)
    lines.push(generateSQL(schema));
    lines.push('');
    lines.push('-- ================================================');
    lines.push('-- Dummy data generated by ERDify AI');
    lines.push('-- ================================================\n');
    lines.push('SET FOREIGN_KEY_CHECKS=0;\n');

    // INSERT statements — in same topological order as CREATE TABLE
    const sorted = topologicalSort(schema.tables);
    sorted.forEach(table => {
        const rows = dummyData[table.name];
        if (!rows || rows.length === 0) return;

        const columnNames = (table.columns as ERColumn[]).map((c: ERColumn) => c.name);
        const colList = columnNames.map((n: string) => `\`${n}\``).join(', ');

        lines.push(`-- Data for table \`${table.name}\``);
        rows.forEach(row => {
            const values = columnNames.map((col: string) => {
                const val = row[col];
                return formatValue(val, (table.columns as ERColumn[]).find((c: ERColumn) => c.name === col)?.type || 'TEXT');
            });
            lines.push(`INSERT INTO \`${table.name}\` (${colList}) VALUES (${values.join(', ')});`);
        });
        lines.push('');
    });

    lines.push('SET FOREIGN_KEY_CHECKS=1;');

    return lines.join('\n');
}

/** Same topological sort as in exportSql.ts */
function topologicalSort(tables: any[]): any[] {
    const nameMap = new Map(tables.map((t: any) => [t.name, t]));
    const visited = new Set<string>();
    const result: any[] = [];

    function visit(name: string, chain: Set<string>) {
        if (visited.has(name)) return;
        if (chain.has(name)) return;
        chain.add(name);
        const table = nameMap.get(name);
        if (table) {
            for (const col of table.columns) {
                if (col.isForeignKey && col.references?.table) {
                    visit(col.references.table, chain);
                }
            }
            if (!visited.has(name)) {
                visited.add(name);
                result.push(table);
            }
        }
        chain.delete(name);
    }

    for (const table of tables) visit(table.name, new Set());
    return result;
}

function formatValue(val: any, type: string): string {
    if (val === null || val === undefined) return 'NULL';

    const t = type.toUpperCase();

    if (typeof val === 'boolean') return val ? '1' : '0';
    if (typeof val === 'number') return String(val);

    const strVal = String(val);

    if (
        t.includes('INT') || t.includes('DECIMAL') || t.includes('NUMERIC') ||
        t.includes('FLOAT') || t.includes('DOUBLE') || t.includes('REAL') || t === 'NUMBER'
    ) {
        const num = parseFloat(strVal);
        return isNaN(num) ? 'NULL' : String(num);
    }

    if (t === 'BOOLEAN' || t === 'BOOL' || t === 'TINYINT(1)') {
        return (strVal.toLowerCase() === 'true' || strVal === '1') ? '1' : '0';
    }

    // Strings — escape single quotes
    return `'${strVal.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function downloadSQL(sql: string, projectName: string): void {
    const blob = new Blob([sql], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${projectName.replace(/\s+/g, '_')}_with_data.sql`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}
